### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by yifan96** [wonderren/public_pymcpf#1]
![image](https://user-images.githubusercontent.com/63547586/202304763-501fb6db-ec1c-4f90-9e0c-3242a5ae061d.png)

![image](https://user-images.githubusercontent.com/63547586/202304723-d3ff16f6-d8b1-4c32-90e2-5511e746734d.png)
Hello, 
I am a new to MCPF problems.
Some index error appears when I try to select some targets randomly.
Could you give me a hint on this? Thanks

**Comment by yifan96** [comment]
Solved. By default, it is set that len(Vo)=len(Vd). Change function for spMat construction in common.py

**Comment by wonderren** [comment]
Hi, just to double check, is this a general error, or an error that only occurs after your customization (by removing the destinations)?

**Comment by yifan96** [comment]
> 
Not a general error. It just appeared after I input different number of starts and destinations in MCPF.
